### PR TITLE
Fix nits in `bn256`.

### LINKED ISSUE #91: Simplify `frobenius_map` in `bn256`
The Frobenius map function is implemented in a rather confusing way:
https://github.com/privacy-scaling-explorations/halo2curves/blob/6e2ff3853c8fe91300650a733100640dacf313e6/src/bn256/fq2.rs#L273-L275

where the precomputed values are:
https://github.com/privacy-scaling-explorations/halo2curves/blob/6e2ff3853c8fe91300650a733100640dacf313e6/src/bn256/fq2.rs#L570-L586

The first value is `Fq(-1)^0 = 1`. The second value is just the Legendre symbol of `-1`. `-1`  is by definition (in this field) a quadratic non-residue, so the second value is `-1`. As a consequence the Frobenius map of an even power maps each element to itself, and odd powers are mapped into the conjugation. (For an in depth explanation check out this blog post: https://alicebob.modp.net/the-frobenius-endomorphism-with-finite-fields/).
This is the way it is implemented in `zkcrypto/bls12_381` : https://github.com/zkcrypto/bls12_381/blob/7de7b9d9c509b9973b35a3241b74bbbea95e700a/src/fp2.rs#L141

### PR DESCRIPTION
**Pull request by davidnevadoc**
Fixes #91 and #90.

This PR removes some unused functions and corrects some comments regarding its constants.

### CODE REVIEW

File: src/bn256/fq2.rs [hunk 1]
```diff
@@ -271,12 +272,14 @@ impl Fq2 {
     }
 
     pub fn frobenius_map(&mut self, power: usize) {
-        self.c1 *= &FROBENIUS_COEFF_FQ2_C1[power % 2];
+        if power % 2 != 0 {
+            self.conjugate()
+        }
```
Comment (CPerezz) [inline src/bn256/fq2.rs:277]: Can't you shift by one to the right and && by a mask? Might be harder to read but we're sure that will always be as optimized as possible.

File: src/bn256/fq2.rs [hunk 2]
```diff
@@ -271,12 +272,14 @@ impl Fq2 {
     }
 
     pub fn frobenius_map(&mut self, power: usize) {
-        self.c1 *= &FROBENIUS_COEFF_FQ2_C1[power % 2];
+        if power % 2 != 0 {
+            self.conjugate()
```
Comment (CPerezz) [inline src/bn256/fq2.rs:276]: Conjugate can't be a `const fn` as it is done "in place". I wonder if we can gain any speedup by not making it get an `&mut` and declaring the fn `const`.

kk since it relies in `Sub` which isn't const this will not work. So this is fine as is.
Just leaving the comment with my reasoning so you can double-check

File: src/bn256/fq6.rs [hunk 3]
```diff
@@ -513,7 +508,7 @@ pub const FROBENIUS_COEFF_FQ6_C1: [Fq2; 6] = [
 ];
 
 pub const FROBENIUS_COEFF_FQ6_C2: [Fq2; 6] = [
-    // Fq2(u + 1)**(((2q^0) - 2) / 3)
+    // Fq2(u + 9)**(((2q^0) - 2) / 3)
```
Comment (CPerezz) [inline src/bn256/fq6.rs:511]: Can you elaborate where's this 9 coming from?

**Review by CPerezz — APPROVED** [review]
Overall LGTM! THanks for addressing these nits! 
Left some comments to briefly discuss/address/elaborate.

File: src/bn256/fq6.rs (hunk 3 above)
Comment (davidnevadoc) [reply src/bn256/fq6.rs:511]: The previous value is the cubic non_residue for `Bls12-381`. The values for the field extensions of Bn are :
```
   Fp2  = Fp[X]  / <X^2 + 1>             alpha^2 = -1
   Fp6  = Fp2[X] / <X^3 - (alpha + 9>    beta^3  = alpha + 9
   Fp12 = Fp6[X] / <X^2 - beta>          gamma^2 = beta
```

File: src/bn256/fq2.rs (hunk 1 above)
Comment (davidnevadoc) [reply src/bn256/fq2.rs:277]: Not sure how to do this properly since `power` is `usize`.
We can use its methods for example:
```  rust
if power.trailing_zeros() != 0 {
    self.conjugate()
        }
```
but I don't think it is worth it.
